apiVersion: v1
kind: Service
metadata:
  name: multistage-test-service
spec:
  selector:
    app: multistage-test
  ports:
    - protocol: TCP
      port: 80          # The port the service will expose
      targetPort: 80    # The container's port inside the Pod
  type: ClusterIP       # Can change to LoadBalancer or NodePort if needed
